<?php

namespace FondOfSpryker\Shared\ContentfulStorage;

class ContentfulStorageConstants
{
    public const CONTENTFUL_SYNC_STORAGE_QUEUE = 'sync.storage.contentful';
    public const CONTENTFUL_SYNC_STORAGE_QUEUE_ERROR = 'sync.storage.contentful.error';
    public const CONTENTFUL_SYNC_STORAGE_SYNCHRONIZATION_POOL_NAME = 'CONTENTFUL_SYNC_STORAGE_SYNCHRONIZATION_POOL_NAME';
    public const CONTENTFUL_SYNC_STORAGE_DEFAULT_SYNCHRONIZATION_POOL_NAME = 'synchronizationPool';

    public const CONTENTFUL_ACCESS_TOKEN = 'CONTENTFUL_ACCESS_TOKEN';
    public const CONTENTFUL_SPACE_ID = 'CONTENTFUL_SPACE_ID';
    public const CONTENTFUL_LOCALE_TO_STORE_LOCALE = 'CONTENTFUL_LOCALE_TO_STORE_LOCALE';
    public const CONTENTFUL_DEFAULT_LOCALE = 'CONTENTFUL_DEFAULT_LOCALE';
    public const CONTENTFUL_FIELD_NAME_ACTIVE = 'CONTENTFUL_FIELD_NAME_ACTIVE';
    public const CONTENTFUL_FIELD_NAME_IDENTIFIER = 'CONTENTFUL_FIELD_NAME_IDENTIFIER';

    public const CONTENTFUL_RESOURCE_NAME = 'contentful';
}
